name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  NODE_VERSION: '16.x'

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
        php-versions: ['7.4', '8.0', '8.1']

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        tools: phpstan, cs2pr, phpcs

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run PHPStan
      run: phpstan analyse src

    - name: Run phpcs
      run: phpcs -q --report=checkstyle src | cs2pr

    - name: Setup php-fpm
      env:
        version: ${{ matrix.php-versions }}
      run: |
        sudo apt-get install php$version-fpm
        sudo cp /usr/sbin/php-fpm$version /usr/bin/php-fpm # copy to /usr/bin
        sudo service php$version-fpm start
        sudo service php$version-fpm status

    - name: install nginx
      run: sudo apt install nginx

    - name: copy nginx config file
      run: |
        sed -i 's/php7.4-fpm/php${{ matrix.php-versions }}-fpm/g' tests/RESTAPI/fusionsuite.conf
        sudo cp tests/RESTAPI/fusionsuite.conf /etc/nginx/sites-available/fusionsuite.conf

    - name: start nginx
      run: sudo systemctl start nginx

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'yarn'
        cache-dependency-path: tests/RESTAPI/yarn.lock

    - name: yarn install
      run: |
        cd tests/RESTAPI/
        yarn install

    - name: run REST API tests
      run: |
        cd tests/RESTAPI/
        ./node_modules/.bin/mocha --ignore "./node_modules/**/*.js" "./**/*.js"

